[package]
description = "Congatec CGOS API Rust Bindings"
edition = "2021"
homepage = "https://github.com/HULKs/cgos-rs"
license = "BSD-2-Clause"
name = "cgos"
version = "0.2.0"

[dependencies]
bitflags = "1.3.2"
thiserror = "1.0.38"

[build-dependencies]
bindgen = "0.63.0"
